### ISSUE TITLE
Windows Gamedata out of date

### ISSUE THREAD

**Issue by ChaseTownsend** [FlaminSarge/tf_maxspeed_patch#3]
The windows gamedata is likely out of date due to this message on map start
[tf_maxspeed_patch.smx] Value at (0x635A2379) was not expected: (0.0000) != 520.0. Cowardly refusing to do things.

**Comment by FlaminSarge** [comment]
Should be fixed by https://github.com/FlaminSarge/tf_maxspeed_patch/commit/5a379a8647a4f67ef43608cc563c4a8a288715ca

Let me know/close this if so.

Also if you don't need to set a particular limit value you could use https://github.com/Mikusch/SourceScramble-Patches/tree/master?tab=readme-ov-file#whats-in-the-box instead, it sets it to maximum value the field can hold instead of looking at a cvar.
